// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 07/04/2026, 22.15.06
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/scraps/rona-asa/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/scraps/rona-asa/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/scraps/rona-asa/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/scraps/rona-asa/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/scraps/rona-asa/plugins/**/*.{js,ts,mjs}","D:/scraps/rona-asa/composables/**/*.{js,ts,mjs}","D:/scraps/rona-asa/utils/**/*.{js,ts,mjs}","D:/scraps/rona-asa/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/scraps/rona-asa/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/scraps/rona-asa/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/scraps/rona-asa/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;